# Generated by Django 5.1.1 on 2024-12-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_master_user_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-id'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
