# Generated by Django 5.1.1 on 2025-06-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_custom_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="status",
        ),
    ]
