# Generated by Django 5.1.1 on 2025-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('busy', 'Busy'), ('available', 'available')], default='available', max_length=10),
        ),
    ]
