services:
    db:
      build: ./deployment/postgres
      container_name: tms_db
      restart: unless-stopped
      expose:
        - "5432"
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - tms_network
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432"
          ]
        interval: 10s
        timeout: 10s
        retries: 10

    web:
        build:
          context: .
        container_name: tms_django
        restart: unless-stopped
        environment:
          - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so.30
        volumes:
          - .:/code
          - ./deployment/gunicorn/logs:/deployment/gunicorn/logs
          - ./static:/code/static
          - ./media:/code/media
        expose:
          - "8000"
        ports:
          - "8010:8000"
        networks:
            - tms_network
        depends_on:
            db:
              condition: service_healthy
            redis:
              condition: service_started

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: tms_pgadmin
        restart: always
        environment:
          - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
          - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        networks:
            - tms_network
        depends_on:
          db:
            condition: service_healthy

#    nginx:
#        build: ./deployment/nginx
#        container_name: tms_nginx
#        restart: unless-stopped
#        ports:
#            - "80:80"
#        networks:
#            - tms_network
#        volumes:
#          - ./static:/code/static
#          - ./media:/code/media
#          - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
#          - ./deployment/nginx/:/etc/nginx/conf.d
#        links:
#          - web
#        depends_on:
#          - web

    redis:
        image: redis:alpine
        container_name: tms_redis
        restart: unless-stopped
        expose:
          - "6379"
        ports:
          - "6379:6379"
        networks:
            - tms_network

    celery:
      build:
        context: .
        dockerfile: ./deployment/celery/celery.dockerfile
      container_name: tms_celery
      environment:
        - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so.30
        - CELERY_BROKER_URL=redis://tms_redis:6379/0
        - PYTHONPATH=/tms-backend:/tms-backend/tms
      restart: unless-stopped
      volumes:
        - .:/tms-backend
        - ./deployment/celery/logs:/deployment/celery/logs
      depends_on:
        - redis
        - web
        - db
      networks:
        - tms_network

    celery_flower:
      build:
        context: .
        dockerfile: ./deployment/celery/flower.dockerfile
      container_name: tms_celery_flower
      environment:
        - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so.30
        - PYTHONPATH=/tms-backend:/tms-backend/tms
#        - FLOWER_URL_PREFIX=/flower
        - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
      restart: unless-stopped
      volumes:
        - .:/tms-backend
        - ./deployment/celery/logs:/deployment/celery/logs
      depends_on:
        - redis
        - web
        - db
        - celery
      networks:
        - tms_network
      expose:
        - "5555"
      ports:
        - "5555:5555"


networks:
    tms_network:
        driver: bridge

volumes:
    postgres_data:
      driver: local
    static:
      driver: local
    media:
        driver: local
