events {
    worker_connections 1024;
}

http {
    # Include MIME types for correct Content-Type headers
    include       mime.types;
    default_type  application/octet-stream;

    upstream tms_backend {
        server web:8000;
    }

    server {
        listen 80;
        server_name  127.0.0.1;

        # Proxy requests to Django application
        location / {
            proxy_pass http://tms_backend; # Match your Django container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve static files
        location /static/ {
            autoindex off;  # Disable directory listing
            alias /code/static/;  # Match STATIC_ROOT in Django
            add_header Cache-Control "public, max-age=3600";  # Optional: Cache headers
        }

        # Serve media files
        location /media/ {
            autoindex off;
            alias /code/media/;  # Match MEDIA_ROOT in Django
        }

        # Handle 404 errors for missing static files
        error_page 404 /404.html;

        # Log file locations (optional)
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }

}