events {
    worker_connections 1024;
}

http {
    upstream tms_backend {
        server web:8000;
    }

    server {
        listen 80;
        charset utf-8;
        server_name  127.0.0.1;

        location / {
            proxy_pass http://tms_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
                autoindex on;
                alias /code/static/;
        }

        location /media/ {
            autoindex on;
            alias /code/media/;
        }
    }

}