# Generated by Django 5.1.1 on 2025-05-27 18:22

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_vehicle_capacity_vehicle_specifications_and_more'),
        ('organisations', '0004_package_organisation_has_route_optimization_and_more'),
        ('users', '0008_customuser_custom_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dispatch_lo_name_ef61e0_idx'), models.Index(fields=['city'], name='dispatch_lo_city_a17990_idx'), models.Index(fields=['postal_code'], name='dispatch_lo_postal__1fe905_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organisations.organisation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='dispatch.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Order Reference')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('in_progress', 'In Progress'), ('delivered', 'delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Order Status')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 is highest priority, 5 is lowest priority', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Priority')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the package in kilograms', max_digits=10, null=True, verbose_name='Package Weight (kg)')),
                ('dimensions', models.JSONField(blank=True, help_text='Dimensions of the package in the format {"length": 0, "width": 0, "height": 0, "unit": "cm"}', null=True, verbose_name='Package Dimensions (LxWxH)')),
                ('description', models.TextField(blank=True, help_text='Description of the order or package', null=True, verbose_name='Order Description')),
                ('instructions', models.TextField(blank=True, help_text='Any special instructions for the order', null=True, verbose_name='Special Instructions')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('pickup_window_start', models.DateTimeField(blank=True, null=True, verbose_name='Pickup Window Start')),
                ('pickup_window_end', models.DateTimeField(blank=True, null=True, verbose_name='Pickup Window End')),
                ('delivery_window_start', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Window Start')),
                ('delivery_window_end', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Window End')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Date Delivered')),
                ('date_cancelled', models.DateTimeField(blank=True, null=True, verbose_name='Date Cancelled')),
                ('date_failed', models.DateTimeField(blank=True, null=True, verbose_name='Date Failed')),
                ('meta_data', models.JSONField(blank=True, help_text='Additional metadata for the order', null=True, verbose_name='Meta Data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='dispatch.customer', verbose_name='Buyer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver', verbose_name='Driver')),
                ('drop_off', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_off_orders', to='dispatch.location', verbose_name='Drop Off Location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organisations.organisation')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_orders', to='dispatch.location', verbose_name='Pickup Location')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dispatch.customer', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driver_rating', models.PositiveIntegerField(help_text='Driver rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='users.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dispatch.order')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Review',
                'verbose_name_plural': 'Order Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='scheduled', max_length=20, verbose_name='Trip Status')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='Scheduled Start Time')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='Completed Time')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (km)')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Estimated Duration')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Actual Duration')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver', verbose_name='Driver')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_ends', to='dispatch.location', verbose_name='End Location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_starts', to='dispatch.location', verbose_name='Start Location')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-scheduled_start_time'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dispatch.trip', verbose_name='Trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('start', 'Start Location'), ('pickup', 'Pickup'), ('drop_off', 'Dropoff'), ('end', 'End Location')], default='pickup', max_length=10)),
                ('sequence', models.PositiveIntegerField()),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Time of Arrival')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Actual Arrival Time')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Stop Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stops', to='users.driver')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.location')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='dispatch.order')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='dispatch_cu_name_d758db_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='dispatch_cu_email_35094e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='dispatch_cu_phone_n_e52a34_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['rating'], name='dispatch_or_rating_371caf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['driver_rating'], name='dispatch_or_driver__056a39_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='dispatch_tr_status_8e22b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['scheduled_start_time'], name='dispatch_tr_schedul_3a9ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference'], name='dispatch_or_referen_713b70_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='dispatch_or_status_f87029_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['scheduled_date'], name='dispatch_or_schedul_d193bd_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'sequence'], name='dispatch_tr_trip_id_0b25d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['status'], name='dispatch_tr_status_b4ec25_idx'),
        ),
    ]
