# Generated by Django 5.1.1 on 2025-06-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
    ]
