# Generated by Django 5.1.1 on 2025-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('arrived_at_pickup', 'Arrived at Pickup'), ('arrived_at_drop_off', 'Arrived at Drop-off'), ('delivered', 'delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
    ]
