# Generated by Django 5.1.1 on 2025-06-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_customer_location_and_more'),
        ('organisations', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='buyer_orders',
                to='organisations.customer',
                verbose_name='Buyer',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='organisations.customer',
                verbose_name='Recipient',
            ),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
