# Generated by Django 5.1.1 on 2025-09-28 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_alter_order_status'),
        ('organisations', '0006_package_has_route_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='organization',
            # field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='organisations.organisation'),
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='organisations.organisation'),
            preserve_default=False,
        ),
    ]
