# Generated by Django 5.1.1 on 2025-09-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('fleet', '0001_initial'),
        ('organisations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_by_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='added_order',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='buyer_orders',
                to='organisations.customer',
                verbose_name='Buyer',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='drop_off',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='drop_off_orders',
                to='dispatch.location',
                verbose_name='Drop Off Location',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organisations.organisation'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pickup_orders',
                to='dispatch.location',
                verbose_name='Pickup Location',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='organisations.customer',
                verbose_name='Recipient',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='organisations.store',
            ),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='driver',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='users.driver'
            ),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dispatch.order'
            ),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='reviewed_by',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trips',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='organisation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trips',
                to='organisations.organisation',
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='fleet.vehicle',
                verbose_name='Vehicle',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='dispatch.trip',
                verbose_name='Trip',
            ),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='completed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='completed_stops',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stops',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stops',
                to='dispatch.order',
            ),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.trip'
            ),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='dispatch_lo_name_ef61e0_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='dispatch_lo_city_a17990_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['postal_code'], name='dispatch_lo_postal__1fe905_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(
                fields=('reference_number', 'organisation'), name='unique_ref_number_org'
            ),
        ),
    ]
