# Generated by Django 5.1.1 on 2025-09-30 16:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_trip_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_location',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='location',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='End Point Coordinates'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Start Point Coordinates'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(blank=True, default='scheduled', max_length=20, null=True, verbose_name='Trip Status'),
        ),
    ]
