# Generated by Django 5.1.1 on 2025-06-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_alter_location_address_alter_location_city_and_more'),
        ('organisations', '0007_rename_organization_customer_organisation'),
        ('users', '0009_remove_driver_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='dispatch_or_referen_713b70_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='organization',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reference',
        ),
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Order Reference Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='organisations.store',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference_number'], name='dispatch_or_referen_870a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['reference_number', 'organisation'], name='dispatch_or_referen_790536_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='dispatch_or_status_d8d9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'date_delivered'], name='dispatch_or_status_333131_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(
                fields=('reference_number', 'organisation'), name='unique_ref_number_org'
            ),
        ),
    ]
