# Generated by Django 5.1.1 on 2025-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_tripstop_notifications_tripstop_sla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('completed', 'Completed'),
                    ('on_going', 'On Going'),
                    ('pending', 'Pending'),
                    ('assigned', 'Assigned'),
                ],
                default='pending',
                max_length=20,
                null=True,
                verbose_name='Trip Status',
            ),
        ),
    ]
