# Generated by Django 5.1.1 on 2025-09-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_remove_trip_end_location_remove_trip_start_location_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='dispatch_tr_status_8e22b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='dispatch_tr_schedul_3a9ca8_idx',
        ),
    ]
