# Generated by Django 5.1.1 on 2025-06-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_remove_order_dispatch_or_referen_713b70_idx_and_more'),
        ('fleet', '0005_driverprofilelogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.AddField(
            model_name='order',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text='Weight of the package in kilograms',
                max_digits=10,
                null=True,
                verbose_name='Package Weight (kg)',
            ),
        ),
    ]
