# Generated by Django 5.1.1 on 2025-07-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_remove_order_driver_order_driver_profile_and_more'),
        ('fleet', '0005_driverprofilelogs'),
        ('organisations', '0007_rename_organization_customer_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='tripstop',
            options={
                'ordering': ['trip', 'sequence', 'stop_type'],
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
            },
        ),
        migrations.RemoveIndex(
            model_name='tripstop',
            name='dispatch_tr_status_b4ec25_idx',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='actual_arrival',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='status',
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_geometry',
            field=models.TextField(blank=True, help_text='The actual geometry', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trips',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='organisation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trips',
                to='organisations.organisation',
            ),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_geometry',
            field=models.TextField(blank=True, help_text='The planned geometry', null=True),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='driver_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stops',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated Duration in Seconds', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.ForeignKey(
                help_text='Can be used for round trips',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='trip_ends',
                to='dispatch.location',
                verbose_name='End Location',
            ),
        ),
        migrations.AlterField(
            model_name='trip',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Start Time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'scheduled'),
                    ('pending', 'pending'),
                    ('on_going', 'on_going'),
                    ('complete', 'complete'),
                ],
                default='pending',
                max_length=10,
                verbose_name='Trip Status',
            ),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='completed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='completed_stops',
                to='fleet.driverprofile',
            ),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver_profile'], name='dispatch_tr_driver__fd3706_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organisation'], name='dispatch_tr_organis_f14335_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organisation', 'status'], name='dispatch_tr_organis_339502_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organisation', 'created_at'], name='dispatch_tr_organis_57201e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organisation', 'completed_time'], name='dispatch_tr_organis_7caf55_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organisation', 'scheduled_start_time'], name='dispatch_tr_organis_4816e2_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['stop_type'], name='dispatch_tr_stop_ty_da158a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['driver_profile'], name='dispatch_tr_driver__860233_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['order'], name='dispatch_tr_order_i_0aded4_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'order'], name='dispatch_tr_trip_id_53d227_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'driver_profile'], name='dispatch_tr_trip_id_0a77a9_idx'),
        ),
    ]
