# Generated by Django 5.1.1 on 2025-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_alter_trip_options_alter_tripstop_options_and_more'),
        ('fleet', '0005_driverprofilelogs'),
        ('organisations', '0007_rename_organization_customer_organisation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trip'], name='dispatch_or_trip_id_c8b37f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation'], name='dispatch_or_organis_447421_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation', 'status'], name='dispatch_or_organis_592743_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organisation', 'driver_profile'], name='dispatch_or_organis_696f0c_idx'),
        ),
    ]
