# Generated by Django 5.1.1 on 2025-07-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_order_dispatch_or_trip_id_c8b37f_idx_and_more'),
        ('organisations', '0007_rename_organization_customer_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='locations',
                to='organisations.organisation',
            ),
        ),
    ]
