# Generated by Django 5.1.1 on 2025-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_location_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='stop_type',
            field=models.CharField(
                choices=[
                    ('start', 'Start Location'),
                    ('at_store', 'Arrive at Store'),
                    ('pickup', 'Pickup'),
                    ('at_drop_off', 'Arrive at Drop Off'),
                    ('drop_off', 'Dropoff'),
                    ('end', 'End Location'),
                ],
                default='pickup',
                max_length=20,
            ),
        ),
    ]
