# Generated by Django 5.1.1 on 2025-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_tripstop_stop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
