# Generated by Django 5.1.1 on 2025-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_alter_tripstop_stop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('pending', 'Pending'),
                    ('broadcasted', 'Broadcasted'),
                    ('at_store', 'At Store'),
                    ('in_transit', 'In Transit'),
                    ('at_drop_off', 'At Drop Off'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Order Status',
            ),
        ),
    ]
