# Generated by Django 5.1.1 on 2025-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('pending', 'Pending'),
                    ('broadcasted', 'Broadcasted'),
                    ('assigned', 'Assigned'),
                    ('at_store', 'At Store'),
                    ('in_transit', 'In Transit'),
                    ('at_drop_off', 'At Drop Off'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                    ('failed', 'Failed'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Order Status',
            ),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='stop_type',
            field=models.CharField(
                choices=[
                    ('start', 'Start'),
                    ('end', 'End'),
                    ('at_store', 'At Store'),
                    ('pickup', 'Pickup'),
                    ('at_drop_off', 'At Drop Off'),
                    ('drop_off', 'Drop Off'),
                ],
                default='pickup',
                max_length=20,
            ),
        ),
    ]
