# Generated by Django 5.1.1 on 2025-09-30 17:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('paid', 'Paid'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'payment_details',
                    models.JSONField(blank=True, help_text='Detailed breakdown of payment calculation', null=True),
                ),
            ],
            options={
                'verbose_name': 'Driver Payment',
                'verbose_name_plural': 'Driver Payments',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('busy', 'busy'),
                            ('available', 'available'),
                            ('offline', 'offline'),
                            ('inactive', 'inactive'),
                        ],
                        db_index=True,
                        default='available',
                    ),
                ),
                ('national_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
        migrations.CreateModel(
            name='DriverProfileLogs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Driver Profile Log',
                'verbose_name_plural': 'Driver Profile Logs',
            },
        ),
        migrations.CreateModel(
            name='PaymentDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'deduction_type',
                    models.CharField(
                        choices=[
                            ('vehicle_maintenance', 'Vehicle Maintenance'),
                            ('insurance', 'Insurance'),
                            ('penalty', 'Penalty'),
                            ('other', 'Other'),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payment Deduction',
                'verbose_name_plural': 'Payment Deductions',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'model_type',
                    models.CharField(
                        choices=[
                            ('fixed', 'Fixed Rate'),
                            ('commission', 'Commission Based'),
                            ('distance', 'Distance Based'),
                            ('time', 'Time Based'),
                            ('hybrid', 'Hybrid'),
                        ],
                        max_length=20,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'base_rate',
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text='Base rate per delivery/trip', max_digits=10, null=True
                    ),
                ),
                (
                    'commission_percentage',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Commission percentage of the delivery fee',
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'rate_per_km',
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text='Rate per kilometer', max_digits=10, null=True
                    ),
                ),
                (
                    'minimum_distance_fee',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Minimum fee for short distances',
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    'hourly_rate',
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text='Rate per hour', max_digits=10, null=True
                    ),
                ),
                (
                    'minimum_hours',
                    models.PositiveIntegerField(blank=True, help_text='Minimum billable hours', null=True),
                ),
                (
                    'hybrid_config',
                    models.JSONField(blank=True, help_text='Configuration for hybrid payment model', null=True),
                ),
                ('bonus_rules', models.JSONField(blank=True, help_text='Rules for performance bonuses', null=True)),
            ],
            options={
                'verbose_name': 'Payment Model',
                'verbose_name_plural': 'Payment Models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                (
                    'source',
                    models.CharField(
                        choices=[('in_house', 'in_house'), ('third_party', 'third_party')],
                        default='in_house',
                        max_length=11,
                    ),
                ),
                (
                    'vehicle_type',
                    models.CharField(
                        choices=[
                            ('bicycle', 'bicycle'),
                            ('ebike', 'ebike'),
                            ('motorcycle', 'motorcycle'),
                            ('pickup', 'pickup'),
                            ('truck', 'truck'),
                        ],
                        default='motorcycle',
                        max_length=10,
                    ),
                ),
                (
                    'capacity',
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text='Capacity in kg', max_digits=10, null=True
                    ),
                ),
                ('specifications', models.JSONField(blank=True, help_text='Vehicle specifications', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignmentLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Assignment Log',
                'verbose_name_plural': 'Vehicle Assignment Logs',
            },
        ),
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'payment_overrides',
                    models.JSONField(
                        blank=True, help_text='Group-specific overrides for payment model settings', null=True
                    ),
                ),
                (
                    'minimum_rating',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Minimum rating required for this group',
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    'minimum_completed_trips',
                    models.PositiveIntegerField(
                        blank=True, help_text='Minimum number of completed trips required', null=True
                    ),
                ),
                (
                    'vehicle_requirements',
                    models.JSONField(blank=True, help_text='Vehicle requirements for this group', null=True),
                ),
                (
                    'organisation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='driver_groups',
                        to='organisations.organisation',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Driver Group',
                'verbose_name_plural': 'Driver Groups',
                'ordering': ['name'],
            },
        ),
    ]
