# Generated by Django 5.1.1 on 2025-09-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('organisations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='driver',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.driver'
            ),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='driver_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fleet.drivergroup'
            ),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='users.driver'
            ),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='drivers',
                to='fleet.drivergroup',
            ),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='driver_profiles',
                to='organisations.organisation',
            ),
        ),
        migrations.AddField(
            model_name='driverprofilelogs',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='fleet.driverprofile'
            ),
        ),
        migrations.AddField(
            model_name='driverprofilelogs',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='driver_profile_logs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='paymentdeduction',
            name='payment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='deduction_records', to='fleet.driverpayment'
            ),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_models',
                to='organisations.organisation',
            ),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='payment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.paymentmodel'),
        ),
        migrations.AddField(
            model_name='drivergroup',
            name='payment_model',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='driver_groups', to='fleet.paymentmodel'
            ),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organisations.organisation'
            ),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='fleet.vehicle'
            ),
        ),
        migrations.AddField(
            model_name='vehicleassignmentlogs',
            name='assigned_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_vehicle_assignments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='vehicleassignmentlogs',
            name='driver',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='users.driver'
            ),
        ),
        migrations.AddField(
            model_name='vehicleassignmentlogs',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmodel',
            unique_together={('organisation', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='drivergroup',
            unique_together={('organisation', 'name')},
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['driver', 'status'], name='driver_status_index'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.UniqueConstraint(fields=('driver', 'organisation'), name='unique_driver_organisation'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.UniqueConstraint(fields=('driver', 'vehicle'), name='unique_driver_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='driverprofile',
            constraint=models.UniqueConstraint(
                fields=('national_id', 'organisation'), name='unique_national_id_organisation'
            ),
        ),
    ]
