# Generated by Django 5.1.1 on 2025-05-27 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('organisations', '0004_package_organisation_has_route_optimization_and_more'),
        ('users', '0008_customuser_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='specifications',
            field=models.JSONField(blank=True, help_text='Vehicle specifications', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_overrides', models.JSONField(blank=True, help_text='Group-specific overrides for payment model settings', null=True)),
                ('minimum_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum rating required for this group', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('minimum_completed_trips', models.PositiveIntegerField(blank=True, help_text='Minimum number of completed trips required', null=True)),
                ('vehicle_requirements', models.JSONField(blank=True, help_text='Vehicle requirements for this group', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_groups', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Driver Group',
                'verbose_name_plural': 'Driver Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_details', models.JSONField(blank=True, help_text='Detailed breakdown of payment calculation', null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.driver')),
                ('driver_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fleet.drivergroup')),
            ],
            options={
                'verbose_name': 'Driver Payment',
                'verbose_name_plural': 'Driver Payments',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDeduction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_type', models.CharField(choices=[('vehicle_maintenance', 'Vehicle Maintenance'), ('insurance', 'Insurance'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_records', to='fleet.driverpayment')),
            ],
            options={
                'verbose_name': 'Payment Deduction',
                'verbose_name_plural': 'Payment Deductions',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('fixed', 'Fixed Rate'), ('commission', 'Commission Based'), ('distance', 'Distance Based'), ('time', 'Time Based'), ('hybrid', 'Hybrid')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Base rate per delivery/trip', max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage of the delivery fee', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per kilometer', max_digits=10, null=True)),
                ('minimum_distance_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fee for short distances', max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour', max_digits=10, null=True)),
                ('minimum_hours', models.PositiveIntegerField(blank=True, help_text='Minimum billable hours', null=True)),
                ('hybrid_config', models.JSONField(blank=True, help_text='Configuration for hybrid payment model', null=True)),
                ('bonus_rules', models.JSONField(blank=True, help_text='Rules for performance bonuses', null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_models', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Payment Model',
                'verbose_name_plural': 'Payment Models',
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='payment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.paymentmodel'),
        ),
        migrations.AddField(
            model_name='drivergroup',
            name='payment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_groups', to='fleet.paymentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='drivergroup',
            unique_together={('organisation', 'name')},
        ),
    ]
