# Generated by Django 5.1.1 on 2025-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('busy', 'Busy'), ('available', 'available'), ('inactive', 'Inactive')], db_index=True, default='available'),
        ),
    ]
