# Generated by Django 5.1.1 on 2025-06-24 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_vehicle_capacity_vehicle_specifications_and_more"),
        ("organisations", "0004_package_organisation_has_route_optimization_and_more"),
        ("users", "0009_remove_driver_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="driver",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="organisations.organisation",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(db_index=True, max_length=50)),
                ("last_name", models.CharField(db_index=True, max_length=50)),
                ("active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("busy", "busy"),
                            ("available", "available"),
                            ("offline", "offline"),
                            ("inactive", "inactive"),
                        ],
                        db_index=True,
                        default="available",
                    ),
                ),
                ("national_id", models.CharField(max_length=50)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="users.driver",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profiles",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
                "indexes": [
                    models.Index(
                        fields=["driver", "status"], name="driver_status_index"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("driver", "organisation"),
                        name="unique_driver_organisation",
                    ),
                    models.UniqueConstraint(
                        fields=("driver", "vehicle"), name="unique_driver_vehicle"
                    ),
                    models.UniqueConstraint(
                        fields=("national_id", "organisation"),
                        name="unique_national_id_organisation",
                    ),
                ],
            },
        ),
    ]
