# Generated by Django 5.1.1 on 2025-06-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_vehicle_driver_vehicle_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='drivers',
                to='fleet.drivergroup',
            ),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(
                choices=[
                    ('bicycle', 'bicycle'),
                    ('ebike', 'ebike'),
                    ('motorcycle', 'motorcycle'),
                    ('pickup', 'pickup'),
                    ('truck', 'truck'),
                ],
                default='motorcycle',
                max_length=10,
            ),
        ),
    ]
