# Generated by Django 5.1.1 on 2024-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelTable(
            name='organisation',
            table='organisations',
        ),
    ]
