# Generated by Django 5.1.1 on 2025-05-27 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_users', models.PositiveIntegerField(help_text='Maximum number of users allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_drivers', models.PositiveIntegerField(help_text='Maximum number of drivers allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.JSONField(default=dict, help_text='Features included in this package')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='has_route_optimization',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrganisationPreferences',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('notification_settings', models.JSONField(default=dict, help_text='Notification preferences')),
                ('branding', models.JSONField(default=dict, help_text='Branding settings like colors, logo URL, etc.')),
                ('operational_hours', models.JSONField(default=dict, help_text='Operating hours for each day')),
                ('delivery_settings', models.JSONField(default=dict, help_text='Delivery-related settings')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Preferences',
                'verbose_name_plural': 'Organisation Preferences',
            },
        ),
        migrations.CreateModel(
            name='OrganisationSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organisations.organisation')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisations.package')),
            ],
            options={
                'verbose_name': 'Organisation Subscription',
                'verbose_name_plural': 'Organisation Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['name'],
                'unique_together': {('organisation', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organisations.organisation')),
                ('permissions', models.ManyToManyField(related_name='roles', to='organisations.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
    ]
