# Generated by Django 5.1.1 on 2025-06-25 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_package_organisation_has_route_optimization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.JSONField(default=dict)),
                ('broadcast_radius', models.PositiveIntegerField(default=50, help_text='maximum broadcast radius')),
                (
                    'organisation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='stores',
                        to='organisations.organisation',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['name', 'organisation'], name='name_organisation_index'),
                    models.Index(fields=['key', 'organisation'], name='key_organisation_index'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('name', 'organisation'), name='unique_name_organisation'),
                    models.UniqueConstraint(fields=('key', 'organisation'), name='unique_key_organisation'),
                ],
            },
        ),
    ]
