# Generated by Django 5.1.1 on 2025-09-27 09:12

import commons.constants
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_package_organisation_has_route_optimization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('max_drivers', models.PositiveIntegerField(default=10)),
                ('allow_driver_signup', models.BooleanField(default=True)),
                ('allow_user_signup', models.BooleanField(default=True)),
                ('enable_audit_logs', models.BooleanField(default=True)),
                ('data_retention_days', models.PositiveIntegerField(default=365)),
                ('api_access_enabled', models.BooleanField(default=False)),
                ('custom_terms_of_service', models.TextField(blank=True, null=True)),
                ('custom_privacy_policy', models.TextField(blank=True, null=True)),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('password_expiration_days', models.PositiveIntegerField(default=90)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('order_status_configuration', models.JSONField(default=commons.constants.default_order_status_config, help_text='Configuration for different order statuses')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EST', 'Eastern Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('PST', 'Pacific Standard Time'), ('IST', 'India Standard Time')], default='UTC', max_length=50)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Configuration',
                'verbose_name_plural': 'Organisation Configurations',
            },
        ),
        migrations.DeleteModel(
            name='OrganisationPreferences',
        ),
    ]
