# Generated by Django 5.1.1 on 2025-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_route_optimization',
            field=models.BooleanField(default=False),
        ),
    ]
