# Generated by Django 5.1.1 on 2025-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='organization',
            new_name='organisation',
        ),
    ]
