# Generated by Django 5.1.1 on 2025-07-15 10:41

import organisations.preferences.schemas.trip_stops
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_rename_organization_customer_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpreferences',
            name='trip_stops',
            field=models.JSONField(
                default=organisations.preferences.schemas.trip_stops.default_steps_config,
                help_text='Trip Stops and Notifications',
            ),
        ),
    ]
